### PR TITLE
Switch to SpringOne early bird banner

### PR DESCRIPTION
**Pull request by jacksoncvm**

### CODE REVIEW

**Comment by jacksoncvm** [comment]
@shakuzen current CFP banner expires this Friday, May 3

**Comment by jonatan-ivanov** [comment]
@jacksoncvm Do you want us to wait till 3rd May or can we merge this right now?

**Comment by shakuzen** [comment]
@jacksoncvm Thanks for the PR and heads up on the timeline.
@jonatan-ivanov Personally, I'd want to encourage as many submissions for CFP as possible, so I think we can wait until May 4 to merge since registration will be open for a while.

**Comment by jacksoncvm** [comment]
@jonatan-ivanov @shakuzen 
> Personally, I'd want to encourage as many submissions for CFP as possible, so I think we can wait until May 4 to merge since registration will be open for a while.

That works for me

**Pull request closed without merging**
